export { default as About } from "./About/About";
export { default as Blog } from "./Blog/Blog";
export { default as Careers } from "./Careers/Careers";
export { default as Portfolio } from "./Portfolio/Portfolio";
export { default as Blockchain } from "./Services/Blockchain/Blockchain";
export { default as Contact } from "./Contact/Contact";
export { default as WebAndMobile } from "./Services/Web and Mobile/WebAndMobile";
export { default as MobileApp } from "./Services/MobileApp/MobileApp";
export { default as Cloud } from "./Services/Cloud/Cloud";
export { default as Product } from "./Product/Product";
export { default as NewHome } from "./Home/NewHome";
